"use client";
import { useState } from "react";
import { ArrowDownToLine, ArrowUpRight } from "lucide-react";
import { indexSourceUrl, type IndexProductsDigest, type ThematicBasket } from "@/lib/index-products";
import MetaNote from "./MetaNote";
import { ProbabilityPair, ShiftHistory } from "./BeliefShiftCharts";

const signed = (n: number) => `${n > 0 ? "+" : ""}${n.toFixed(1)}`;
const comparison = {capturing_baseline:"Capturing 24h baseline",basket_changed:"Basket changed · comparison reset",incomplete_pairs:"Comparison coverage limited"};
export function BasketSummary({ product, digest }: {product:ThematicBasket;digest:IndexProductsDigest}) {
  return <>
    <div className="mt-5 flex flex-wrap items-baseline gap-x-2 gap-y-1"><span className="font-mono text-4xl font-medium tracking-tight">{product.headline===null ? "—" : product.headline.toFixed(1)}</span><span className="text-xs text-muted-foreground">index points</span></div>
    <p className="mt-1 text-xs text-muted-foreground">Six-state average · by 31 Dec 2026</p>
    <div className="mt-5 space-y-2">{product.components.map(c=>{
      const row=digest.observations.find(r=>r.marketId===c.marketId), value=!c.issue ? row?.quote?.midpoint : undefined;
      return <div key={c.state} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-x-3 gap-y-1 text-[10px]"><span className="text-muted-foreground">{c.state}</span><div className="order-2 col-span-2 h-1.5 overflow-hidden rounded-full bg-muted-foreground/15"><div className="h-full rounded-full bg-primary" style={{width:`${(value ?? 0)*100}%`}} /></div><span className="order-1 text-right font-mono">{value===undefined ? "—" : `${(value*100).toFixed(1)}%`}</span></div>;
    })}</div>
    <p className="mt-4 text-[11px] text-muted-foreground">{product.change24h===null ? product.comparisonIssue ? comparison[product.comparisonIssue] : "Unavailable" : `${signed(product.change24h)} points over 24h`} · equal weights</p>
  </>;
}

export function BasketDetail({product,digest,onDownload}:{product:ThematicBasket;digest:IndexProductsDigest;onDownload:()=>void}) {
  const [selected,setSelected]=useState(0);
  const component=product.components[selected],row=digest.observations.find(r=>r.marketId===component.marketId);
  const positions=product.components.map((_,i)=>({x:i<3?100:500,y:45+(i%3)*95}));
  return <>
    <div className="mt-6 grid gap-7 lg:grid-cols-2"><div><h4 className="text-xs font-semibold">Six equal components</h4>
      <svg viewBox="0 0 600 280" className="mt-4 hidden w-full sm:block" role="group" aria-label="Arithmetic composition of the six-state basket; select a state to inspect its contract">
        {positions.map((pos,i)=><line key={i} x1={pos.x<300?185:415} y1={pos.y} x2={pos.x<300?235:365} y2="140" className={selected===i ? "stroke-primary" : "stroke-muted-foreground/25"} strokeWidth={selected===i?2:1} />)}
        <rect x="235" y="104" width="130" height="72" rx="14" className="fill-primary/10 stroke-primary/30" />
        <text x="300" y="135" textAnchor="middle" className="fill-foreground font-mono text-[25px]">{product.headline===null ? "—" : product.headline.toFixed(1)}</text><text x="300" y="158" textAnchor="middle" className="fill-muted-foreground text-[12px]">index points</text>
        {product.components.map((c,i)=>{const r=digest.observations.find(r=>r.marketId===c.marketId),p=!c.issue ? r?.quote?.midpoint : undefined,pos=positions[i];return <g key={c.state} role="button" tabIndex={0} aria-pressed={selected===i} aria-label={`${c.state}, ${p===undefined?"unavailable":`${(p*100).toFixed(1)}% quoted probability`}, weight one sixth`} onClick={()=>setSelected(i)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(i);}}} className="cursor-pointer outline-none [&:focus-visible_rect]:stroke-primary [&:focus-visible_rect]:stroke-[3]">
          <rect x={pos.x-85} y={pos.y-35} width="170" height="70" rx="12" className={selected===i?"fill-primary/10 stroke-primary":"fill-card stroke-muted-foreground/25"} />
          <text x={pos.x} y={pos.y-11} textAnchor="middle" className="fill-foreground text-[14px]">{c.state}</text><text x={pos.x} y={pos.y+10} textAnchor="middle" className="fill-primary font-mono text-[18px]">{p===undefined?"Unavailable":`${(p*100).toFixed(1)}%`}</text><text x={pos.x} y={pos.y+27} textAnchor="middle" className="fill-muted-foreground text-[11px]">weight 1/6 · 16.7%</text>
        </g>;})}
      </svg>
      <div className="mt-4 flex flex-wrap gap-2 sm:hidden">{product.components.map((c,i)=>{const r=digest.observations.find(r=>r.marketId===c.marketId),p=!c.issue?r?.quote?.midpoint:undefined;return <button key={c.state} type="button" aria-pressed={selected===i} onClick={()=>setSelected(i)} className={`min-h-20 min-w-0 flex-1 basis-32 rounded-xl border p-3 text-left ${selected===i?"border-primary bg-primary/5":"border-border"}`}><span className="text-xs">{c.state}</span><span className="mt-2 block font-mono text-lg text-primary">{p===undefined?"—":`${(p*100).toFixed(1)}%`}</span><span className="mt-1 block text-[10px] text-muted-foreground">weight 1/6 · 16.7%</span></button>;})}</div>
      <p className="mt-3 text-xs leading-relaxed text-muted-foreground">The level averages these six quoted YES probabilities. Connections show arithmetic composition. They do not imply causal links or the probability of any or all states acting.</p>
      <div className="mt-4 rounded-xl border border-border bg-muted/20 p-4" aria-live="polite"><p className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-primary">{component.state} · exact contract</p>{row ? <><ProbabilityPair row={row} /><a href={indexSourceUrl(row)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-11 items-center gap-1 text-xs text-muted-foreground hover:text-primary">Source contract<ArrowUpRight className="h-3.5 w-3.5" /></a></>:<p className="text-xs">Contract evidence is missing from this capture.</p>}{component.issue && <p className="mt-1 text-xs text-muted-foreground">Withheld: {component.issue.replaceAll("_"," ")}. Its weight remains 1/6.</p>}<p className="mt-2 text-[10px] text-muted-foreground">Enactment window starts {new Date(component.createdAt).toLocaleString()} and ends 31 Dec 2026, 11:59 PM ET.</p></div>
    </div><div><h4 className="mb-4 text-xs font-semibold">Contribution to the 24h change</h4>
      {product.change24h===null ? <p className="rounded-xl bg-muted/40 p-4 text-xs text-muted-foreground">{product.comparisonIssue ? comparison[product.comparisonIssue] : "Comparison unavailable"}. All six comparable pairs are required.</p> : <div className="space-y-3">{product.components.map((c,i)=>{const value=product.contributions[i]!;return <button key={c.state} type="button" aria-pressed={selected===i} onClick={()=>setSelected(i)} className={`w-full rounded-xl border p-3 text-left ${selected===i?"border-primary/50 bg-primary/5":"border-transparent"}`}><div className="flex flex-wrap justify-between gap-x-3 gap-y-1 text-xs"><span>{c.state}</span><span className="font-mono text-primary">{signed(value)} points</span></div><svg viewBox="0 0 300 22" preserveAspectRatio="none" className="mt-2 h-5 w-full" role="img" aria-label={`${c.state} contributes ${value.toFixed(4)} index points to the basket change`}><line x1="10" x2="290" y1="11" y2="11" className="stroke-muted-foreground/20" /><line x1="150" x2="150" y1="3" y2="19" className="stroke-muted-foreground/40" /><rect x={150+Math.min(0,value)*8.4} y="7" width={Math.abs(value)*8.4} height="8" rx="2" className="fill-primary" />{value===0&&<circle cx="150" cy="11" r="2" className="fill-primary" />}</svg></button>;})}<div className="flex flex-wrap items-center gap-1 text-xs text-muted-foreground [&_button]:min-h-11 [&_button]:min-w-11"><p>Total {signed(product.change24h)} index points. Rounded components may differ from the displayed total.</p><MetaNote kind="method" title="Displayed rounding"><p>Weights are exactly 1/6. Contributions sum before rounding to {product.contributions.reduce<number>((s,n)=>s+n!,0)} index points. Each displayed value is rounded independently; no constituent is adjusted to force the displayed sum.</p></MetaNote></div></div>}
      <h4 className="mb-3 mt-6 text-xs font-semibold">Basket level · saved trend</h4><ShiftHistory product={product} />
    </div></div>
    <details className="mt-6 border-t border-border text-xs"><summary className="flex min-h-11 cursor-pointer items-center font-medium">Definition, coverage and source evidence</summary><p className="leading-relaxed text-muted-foreground">A statewide statutory or constitutional moratorium on new data centres, including all new facilities above 100 MW. Local bans, tax-incentive suspensions and executive orders do not qualify. Enactment, rather than the effective date, determines resolution. This fixed six-state sample is not a survey of every state. Missing or incompatible components are never replaced or reweighted.</p><p className="mt-3 text-muted-foreground">{product.coverage.usable}/6 current quotes · {product.coverage.comparable}/6 comparable pairs. {digest.baselineAt?`Baseline ${new Date(digest.baselineAt).toLocaleString()}.`:"No saved 24-hour baseline yet."}</p><ul className="mt-3 divide-y divide-border">{product.components.map(c=>{const r=digest.observations.find(r=>r.marketId===c.marketId);return <li key={c.state} className="py-3">{r ? <a href={indexSourceUrl(r)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-1 hover:text-primary">{c.state} · fixed weight 1/6<ArrowUpRight className="h-3.5 w-3.5" /></a> : <span>{c.state} · fixed weight 1/6</span>}<p className="mt-1 text-muted-foreground">{r?.quote?`Raw YES bid ${(r.quote.bid*100).toFixed(2)}% · ask ${(r.quote.ask*100).toFixed(2)}% · record updated ${new Date(r.quote.updatedAt).toLocaleString()}`:`Quote unavailable: ${c.issue ?? r?.issue ?? "missing"}`}</p></li>;})}</ul></details>
    <button type="button" onClick={onDownload} className="mt-3 inline-flex min-h-11 items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowDownToLine className="h-3.5 w-3.5" />Download evidence</button>
  </>;
}
